//importing the 'mongoose' module
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

//defining the paymentSchema using mongoose.schema
const paymentSchema = new Schema({
    orderId: {type: Schema.Types.ObjectId, ref: 'order', required: true}, //referencing the 'order' model and the objectId that is autogenerated from mongodb
    amount: {type: Number, required: true},
    paymentMethod: {type: String, required: true},
    paymentStatus: {type: String, required: true},
   //do not put card information in here for security reasons. 
   
});

module.exports = mongoose.model("payment", paymentSchema)