//put certain components here to render on every page
"use client"
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '../src/components/Footer'
import {CartContextProvider} from '@/src/components/Cart/cartcontext'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartContextProvider>
          {children}  
        </CartContextProvider>
        <Footer/>
        </body>
    </html>
  )
}
